Update deploy-workspaces.yaml

diff --git a/github/deploy-workspaces.yaml b/github/deploy-workspaces.yaml
--- a/github/deploy-workspaces.yaml
+++ b/github/deploy-workspaces.yaml
@@ -105,3 +105,15 @@ jobs:
     secrets:
       FIREFLY_ACCESS_KEY: ${{ secrets.FIREFLY_ACCESS_KEY }}
       FIREFLY_SECRET_KEY: ${{ secrets.FIREFLY_SECRET_KEY }}
+
+  summary:
+    runs-on: ubuntu-latest
+    needs: deploy-workspaces
+    if: always()
+    steps:
+      - name: Check deploy-workspaces results
+        run: |
+          if [[ "${{ needs.deploy-workspaces.result }}" == "failure" ]]; then
+            echo "Deploy workspaces failed"
+            exit 1
+          fi
